"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ClipboardList, MessageSquareHeart, Users } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { useAuth } from "@/lib/context/auth-context";
import { useTerminology } from "@/lib/hooks/use-terminology";

export default function BpAdminPage() {
  const { activeOrganizationId } = useAuth(); const t = useTerminology(); const isEnglish = t.language === "en";
  const [reports, setReports] = useState<any[]>([]); const [studentCount, setStudentCount] = useState(0);
  useEffect(() => { if (!activeOrganizationId) return; Promise.all([
    supabase.from("bp_reports").select("id, title, created_at, students(name), profiles:created_by(name)").eq("organization_id", activeOrganizationId).order("created_at", { ascending: false }).limit(12),
    supabase.from("students").select("id", { count: "exact", head: true }).eq("organization_id", activeOrganizationId).or("is_removed.is.null,is_removed.eq.false"),
  ]).then(([reportsResult, studentsResult]) => { setReports(reportsResult.data ?? []); setStudentCount(studentsResult.count ?? 0); }); }, [activeOrganizationId]);
  return <div className="mx-auto max-w-5xl space-y-6"><section className="rounded-[2rem] bg-slate-900 p-7 text-white" style={{ boxShadow: "0 5px 0 #000" }}><div className="flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-brand-500"><MessageSquareHeart className="h-6 w-6" /></div><div><p className="text-[10px] font-black uppercase tracking-widest text-brand-300">{isEnglish ? "Counselling mode" : "Mode BK"}</p><h1 className="mt-1 text-2xl font-black">{isEnglish ? "Counselling overview" : "Ringkasan bimbingan"}</h1><p className="mt-2 max-w-2xl text-sm font-bold leading-relaxed text-slate-300">{isEnglish ? "A clear view of counselling notes and follow-up, kept separate from CMS progress." : "Pantau catatan bimbingan dan tindak lanjut secara jelas, terpisah dari progres CMS."}</p></div></div></section><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border-2 border-slate-100 bg-white p-5"><Users className="h-5 w-5 text-brand-600" /><p className="mt-3 text-3xl font-black text-slate-800">{studentCount}</p><p className="text-xs font-black uppercase tracking-widest text-slate-400">{isEnglish ? `Active ${t.santri}s` : `${t.santri} aktif`}</p></div><div className="rounded-2xl border-2 border-slate-100 bg-white p-5"><ClipboardList className="h-5 w-5 text-brand-600" /><p className="mt-3 text-3xl font-black text-slate-800">{reports.length}</p><p className="text-xs font-black uppercase tracking-widest text-slate-400">{isEnglish ? "Recent counselling notes" : "Catatan bimbingan terbaru"}</p></div></div><section className="rounded-2xl border-2 border-slate-100 bg-white"><div className="border-b-2 border-slate-100 px-5 py-4"><h2 className="font-black text-slate-800">{isEnglish ? "Latest counselling notes" : "Catatan bimbingan terbaru"}</h2></div><div className="divide-y-2 divide-slate-50">{reports.map((report) => <Link key={report.id} href={`/bp/reports/${report.id}`} className="flex items-center justify-between gap-4 px-5 py-4 hover:bg-slate-50"><div className="min-w-0"><p className="truncate font-black text-slate-800">{report.title}</p><p className="mt-1 text-xs font-bold text-slate-400">{report.students?.name ?? t.santri} • {new Date(report.created_at).toLocaleString(isEnglish ? "en-US" : "id-ID", { dateStyle: "medium", timeStyle: "short" })}</p></div><span className="text-xs font-black text-brand-700">{isEnglish ? "Open" : "Buka"}</span></Link>)}{!reports.length && <p className="px-5 py-10 text-center text-sm font-bold text-slate-400">{isEnglish ? "No counselling notes yet." : "Belum ada catatan bimbingan."}</p>}</div></section></div>;
}
