-- Seed: example profile_summary values for existing students
-- Run in Supabase SQL editor AFTER add_student_scores.sql.
--
-- Replace the UUIDs below with real student IDs from your students table.
-- You can find them by running: SELECT id, name FROM students LIMIT 10;
--
-- These are example AI-style profiles (150–200 words each, in Indonesian).
-- In production the profiles are auto-generated by generateStudentProfile()
-- after each report is saved.

-- Example 1 — Karakter kuat, perlu penguatan mental
UPDATE public.students
SET profile_summary = 'Ahmad Fauzi adalah santri yang menunjukkan karakter kepemimpinan alami yang cukup menonjol sejak laporan pertama. Ia konsisten hadir tepat waktu, menjaga kebersihan lingkungan, dan aktif membantu teman-teman yang kesulitan dalam hafalan. Pola kekuatannya yang paling konsisten adalah kejujuran dan tanggung jawab — dua sub-indikator yang muncul di hampir semua laporan observasinya.

Area yang masih membutuhkan perhatian adalah ketahanan mental ketika menghadapi tekanan akademis. Ia cenderung mudah menyerah saat mendapat nilai rendah dan perlu dorongan eksternal agar kembali termotivasi. Ustadz disarankan untuk memberikan afirmasi yang lebih sering dan menyertakan Ahmad dalam diskusi kelompok kecil untuk membangun kepercayaan dirinya.

Secara keseluruhan, Ahmad adalah santri yang sangat responsif terhadap bimbingan langsung. Potensi kepemimpinannya akan berkembang optimal jika mendapat tantangan struktural yang sesuai — misalnya menjadi ketua kelompok hafalan.'
WHERE name = 'Ahmad Fauzi';

-- Example 2 — Soft skill menonjol, karakter masih berkembang
UPDATE public.students
SET profile_summary = 'Umar Abdurrahman adalah santri dengan kecerdasan verbal yang tinggi dan kemampuan komunikasi yang sudah melampaui usianya. Ia mampu menyampaikan pendapat dengan jernih, mendengarkan dengan aktif, dan menjadi jembatan komunikasi antarkelompok. Soft skill yang paling konsisten muncul adalah kemampuan bernegosiasi dan empati terhadap sesama.

Di sisi karakter, beberapa aspek masih dalam tahap perkembangan — terutama kedisiplinan waktu dan pengendalian diri ketika sedang tidak sepakat dengan keputusan ustadz. Dalam dua laporan terakhir, tercatat beberapa episode di mana ia merespons kritik dengan defensif, meskipun intensitasnya sudah menurun.

Umar sangat dipengaruhi oleh dinamika sosial di sekitarnya. Strategi yang efektif adalah melibatkannya dalam program mentoring sebaya — perannya sebagai "penjembatan" akan memperkuat rasa tanggung jawabnya sekaligus memberi ruang untuk pertumbuhan karakter yang lebih organik.'
WHERE name = 'Umar Abdurrahman';

-- Example 3 — Profil seimbang
UPDATE public.students
SET profile_summary = 'Hamzah Fansuri menunjukkan profil perkembangan yang relatif seimbang di tiga dimensi utama CIA. Karakter dasarnya kuat — ia jujur, disiplin, dan menghormati autoritas dengan tulus, bukan sekadar formalitas. Mental resiliencenya juga di atas rata-rata: ia mampu bangkit cepat setelah kegagalan dan tidak ragu meminta bantuan ketika bingung.

Yang masih perlu dikembangkan adalah inisiatif. Hamzah cenderung menunggu instruksi sebelum bertindak dan jarang mengajukan pertanyaan secara mandiri. Pola ini konsisten muncul di seluruh laporan: ia adalah pelaksana yang sangat baik, namun inisiator yang pasif.

Fokus penanganan berikutnya disarankan di area soft skill — khususnya kepemimpinan proaktif dan kreativitas dalam pemecahan masalah. Pendekatan yang terbukti efektif: beri ia "tugas terbuka" yang tidak punya jawaban tunggal, sehingga ia terbiasa bekerja tanpa panduan yang tersedia.'
WHERE name = 'Hamzah Fansuri';
